language: java
jdk: [ openjdk8 ]
script: .utility/do-build.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "target/*.jar"
  on:
    tags: true
